---
apiVersion: v1
kind: Namespace
metadata:
  name: adam
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adam
  namespace: adam
spec:
  selector:
    matchLabels:
      name: adam
  template:
    metadata:
      labels:
        name: adam
    spec:
      containers:
      - name: adam
        image: l1fetech/adam:latest
        ports:
        - name: http
          containerPort: 11434
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: adam
  namespace: adam
spec:
  type: ClusterIP
  selector:
    name: adam
  ports:
  - port: 80
    name: http
    targetPort: http
    protocol: TCP
